apiVersion: v1
kind: Service
metadata:
  name: cloudeco-service
  namespace: cloudeco
spec:
  type: NodePort
  selector:
    app: cloudeco
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000